service:
  name: crud-subs

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  auth:
    handler: auth.authorize
  hello:
    handler: handlers/list-subs.handle
    events:
      - http:
          method: get
          path: subscriptions
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
